export type Animal = { slug: string; name: string; keywords: string[] };

export const ANIMALS: Animal[] = [
  { slug: "deer",       name: "Deer",       keywords: ["wildlife", "mammal", "antler", "stag", "nature"] },
  { slug: "panda",      name: "Panda",      keywords: ["cute", "bear", "zoo", "face"] },
  { slug: "tiger",      name: "Tiger",      keywords: ["head", "face", "cat", "stripe"] },
  { slug: "lion",       name: "Lion",       keywords: ["head", "face", "king", "mane", "leo"] },
  { slug: "squirrel",   name: "Squirrel",   keywords: ["autumn", "fall", "season", "forest"] },
  { slug: "koala",      name: "Koala",      keywords: ["bear", "baby", "safari", "cute"] },
  { slug: "rabbit",     name: "Rabbit",     keywords: ["bunny", "rodent", "pet", "cute"] },
  { slug: "horse",      name: "Horse",      keywords: ["stallion", "equestrian", "equine", "mustang", "mammal", "farm"] },
  { slug: "sheep",      name: "Sheep",      keywords: ["goat", "face", "wool", "farm", "cute"] },
  { slug: "bear",       name: "Bear",       keywords: ["grizzly", "forest", "face", "wildlife"] },
  { slug: "cow",        name: "Cow",        keywords: ["mammal", "horns", "face", "farm"] },
  { slug: "frog",       name: "Frog",       keywords: ["amphibian", "nature"] },
  { slug: "boar",       name: "Boar",       keywords: ["pig", "wild", "forest"] },
  { slug: "panther",    name: "Panther",    keywords: ["logo", "mascot", "predator", "speed", "wildlife"] },
  { slug: "raccoon",    name: "Raccoon",    keywords: ["cute", "wild", "forest", "face", "fur"] },
  { slug: "elephant",   name: "Elephant",   keywords: ["face", "mammoth", "trunk", "zoo", "cute"] },
  { slug: "bison",      name: "Bison",      keywords: ["bull", "ox", "buffalo", "portrait", "head", "cattle", "wild"] },
  { slug: "hippo",      name: "Hippo",      keywords: ["shape", "silhouette", "safari"] },
  { slug: "cat",        name: "Cat",        keywords: ["kitty", "kitten", "pet", "cute", "kawaii"] },
  { slug: "rhinoceros", name: "Rhinoceros", keywords: ["rhino", "wild", "zoo", "mammal", "head"] },
  { slug: "monkey",     name: "Monkey",     keywords: ["primate", "mammal", "wildlife"] },
  { slug: "pig",        name: "Pig",        keywords: ["face", "avatar", "farm", "cute"] },
  { slug: "giraffe",    name: "Giraffe",    keywords: ["neck", "safari", "zoo", "jungle", "mammal", "cute"] },
  { slug: "mouse",      name: "Mouse",      keywords: ["rat", "rodent", "pet", "small", "wildlife"] },
  { slug: "gorilla",    name: "Gorilla",    keywords: ["ape", "primate", "strong", "wild", "chimpanzee"] },
];
