export type EmojiEntry = { emoji: string; name: string; keywords: string[] };

export const EMOJIS: EmojiEntry[] = [
  // Smileys & emotion
  { emoji: "😀", name: "grinning", keywords: ["happy", "smile", "joy"] },
  { emoji: "😄", name: "grin", keywords: ["happy", "smile", "laugh"] },
  { emoji: "😊", name: "blush", keywords: ["happy", "smile", "warm"] },
  { emoji: "😇", name: "angel", keywords: ["innocent", "halo", "good"] },
  { emoji: "😍", name: "heart eyes", keywords: ["love", "adore", "crush"] },
  { emoji: "🤩", name: "starstruck", keywords: ["excited", "star", "wow"] },
  { emoji: "😎", name: "cool", keywords: ["sunglasses", "confident", "swag"] },
  { emoji: "🤔", name: "thinking", keywords: ["hmm", "ponder", "wonder"] },
  { emoji: "🤗", name: "hugging", keywords: ["hug", "warmth", "embrace"] },
  { emoji: "😴", name: "sleeping", keywords: ["tired", "zzz", "rest"] },
  { emoji: "😢", name: "cry", keywords: ["sad", "tear", "upset"] },
  { emoji: "😭", name: "sob", keywords: ["crying", "sad", "tears"] },
  { emoji: "😡", name: "angry", keywords: ["mad", "rage", "furious"] },
  { emoji: "🤬", name: "rage", keywords: ["mad", "angry", "cursing"] },
  { emoji: "😱", name: "scream", keywords: ["shocked", "horror", "scared"] },
  { emoji: "🤯", name: "mind blown", keywords: ["exploding", "shocked", "wow"] },
  { emoji: "😈", name: "devil", keywords: ["evil", "mischief", "smirk"] },
  { emoji: "👻", name: "ghost", keywords: ["spooky", "boo", "halloween"] },
  { emoji: "💀", name: "skull", keywords: ["death", "dead", "bones"] },
  { emoji: "🤣", name: "rofl", keywords: ["laugh", "rolling", "funny"] },
  { emoji: "😂", name: "joy", keywords: ["laugh", "funny", "tears"] },
  { emoji: "🥹", name: "touched", keywords: ["emotional", "grateful", "moved"] },
  { emoji: "🥺", name: "pleading", keywords: ["puppy eyes", "please", "beg"] },
  { emoji: "😤", name: "triumph", keywords: ["huff", "proud", "pout"] },
  { emoji: "😒", name: "unamused", keywords: ["meh", "bored", "whatever"] },
  { emoji: "🙄", name: "eye roll", keywords: ["annoyed", "whatever", "sigh"] },
  { emoji: "😏", name: "smirk", keywords: ["sneaky", "sly", "know"] },
  { emoji: "😜", name: "wink tongue", keywords: ["silly", "joke", "playful"] },
  { emoji: "🤪", name: "crazy", keywords: ["silly", "zany", "wild"] },
  { emoji: "😬", name: "grimace", keywords: ["awkward", "nervous", "oops"] },
  { emoji: "🫠", name: "melting", keywords: ["melt", "hot", "overwhelmed"] },
  { emoji: "🤑", name: "money mouth", keywords: ["rich", "cash", "money"] },
  { emoji: "😵", name: "dizzy", keywords: ["knocked out", "confused", "spinning"] },
  { emoji: "🫡", name: "salute", keywords: ["respect", "yes sir", "roger"] },
  { emoji: "🤭", name: "hand over mouth", keywords: ["whoops", "secret", "giggle"] },

  // People & hands
  { emoji: "👋", name: "wave", keywords: ["hello", "hi", "bye"] },
  { emoji: "🙌", name: "raised hands", keywords: ["celebration", "hooray", "praise"] },
  { emoji: "👏", name: "clap", keywords: ["applause", "bravo", "congrats"] },
  { emoji: "💪", name: "muscle", keywords: ["strong", "flex", "power"] },
  { emoji: "🫶", name: "heart hands", keywords: ["love", "care", "affection"] },
  { emoji: "🙏", name: "pray", keywords: ["please", "thanks", "namaste"] },
  { emoji: "👍", name: "thumbs up", keywords: ["good", "yes", "approve"] },
  { emoji: "👎", name: "thumbs down", keywords: ["bad", "no", "disapprove"] },
  { emoji: "✌️", name: "peace", keywords: ["victory", "two", "peace"] },
  { emoji: "🤞", name: "fingers crossed", keywords: ["luck", "hope", "wish"] },
  { emoji: "🤜", name: "fist bump", keywords: ["punch", "bump", "power"] },
  { emoji: "👀", name: "eyes", keywords: ["look", "see", "stare", "watching"] },
  { emoji: "🧠", name: "brain", keywords: ["smart", "think", "intelligence"] },
  { emoji: "💃", name: "woman dancing", keywords: ["dance", "party", "fun"] },
  { emoji: "🕺", name: "man dancing", keywords: ["dance", "disco", "party"] },
  { emoji: "🧙", name: "wizard", keywords: ["magic", "mage", "spell"] },
  { emoji: "🦸", name: "superhero", keywords: ["hero", "power", "cape"] },
  { emoji: "🧑‍💻", name: "technologist", keywords: ["coder", "developer", "computer"] },
  { emoji: "🎅", name: "santa", keywords: ["christmas", "holiday", "gift"] },
  { emoji: "🧜", name: "merperson", keywords: ["mermaid", "ocean", "fantasy"] },

  // Animals
  { emoji: "🐶", name: "dog", keywords: ["puppy", "pet", "woof"] },
  { emoji: "🐱", name: "cat", keywords: ["kitty", "pet", "meow"] },
  { emoji: "🐭", name: "mouse", keywords: ["rodent", "small", "squeak"] },
  { emoji: "🐹", name: "hamster", keywords: ["pet", "cute", "small"] },
  { emoji: "🐰", name: "rabbit", keywords: ["bunny", "cute", "hop"] },
  { emoji: "🦊", name: "fox", keywords: ["clever", "sly", "orange"] },
  { emoji: "🐻", name: "bear", keywords: ["cute", "forest", "grizzly"] },
  { emoji: "🐼", name: "panda", keywords: ["cute", "china", "bamboo"] },
  { emoji: "🐨", name: "koala", keywords: ["marsupial", "australia", "cute"] },
  { emoji: "🐯", name: "tiger", keywords: ["wild", "stripe", "roar"] },
  { emoji: "🦁", name: "lion", keywords: ["king", "roar", "mane"] },
  { emoji: "🐮", name: "cow", keywords: ["moo", "farm", "milk"] },
  { emoji: "🐷", name: "pig", keywords: ["oink", "farm", "bacon"] },
  { emoji: "🐸", name: "frog", keywords: ["green", "ribbit", "jump"] },
  { emoji: "🐵", name: "monkey", keywords: ["ape", "banana", "jungle"] },
  { emoji: "🐔", name: "chicken", keywords: ["hen", "farm", "cluck"] },
  { emoji: "🐧", name: "penguin", keywords: ["cold", "cute", "bird"] },
  { emoji: "🦆", name: "duck", keywords: ["quack", "water", "bird"] },
  { emoji: "🦅", name: "eagle", keywords: ["bird", "majestic", "fly"] },
  { emoji: "🦉", name: "owl", keywords: ["wise", "night", "hoot"] },
  { emoji: "🦇", name: "bat", keywords: ["night", "vampire", "fly"] },
  { emoji: "🐺", name: "wolf", keywords: ["howl", "wild", "pack"] },
  { emoji: "🐴", name: "horse", keywords: ["pony", "farm", "gallop"] },
  { emoji: "🦄", name: "unicorn", keywords: ["magic", "fantasy", "rainbow"] },
  { emoji: "🐝", name: "bee", keywords: ["honey", "buzz", "sting"] },
  { emoji: "🦋", name: "butterfly", keywords: ["transform", "colorful", "fly"] },
  { emoji: "🐌", name: "snail", keywords: ["slow", "shell", "garden"] },
  { emoji: "🦀", name: "crab", keywords: ["seafood", "ocean", "pinch"] },
  { emoji: "🐙", name: "octopus", keywords: ["tentacles", "ocean", "smart"] },
  { emoji: "🦈", name: "shark", keywords: ["ocean", "fish", "danger"] },
  { emoji: "🐳", name: "whale", keywords: ["ocean", "big", "splash"] },
  { emoji: "🦓", name: "zebra", keywords: ["stripe", "africa", "horse"] },
  { emoji: "🦒", name: "giraffe", keywords: ["tall", "neck", "africa"] },
  { emoji: "🦘", name: "kangaroo", keywords: ["australia", "jump", "pouch"] },
  { emoji: "🐊", name: "crocodile", keywords: ["reptile", "teeth", "snap"] },

  // Food & drink
  { emoji: "🍎", name: "apple", keywords: ["red", "fruit", "healthy"] },
  { emoji: "🍊", name: "orange", keywords: ["citrus", "fruit", "vitamin"] },
  { emoji: "🍋", name: "lemon", keywords: ["citrus", "sour", "yellow"] },
  { emoji: "🍇", name: "grapes", keywords: ["purple", "fruit", "wine"] },
  { emoji: "🍓", name: "strawberry", keywords: ["red", "sweet", "berry"] },
  { emoji: "🥝", name: "kiwi", keywords: ["green", "fruit", "tropical"] },
  { emoji: "🍑", name: "peach", keywords: ["fuzzy", "sweet", "fruit"] },
  { emoji: "🥑", name: "avocado", keywords: ["green", "healthy", "guac"] },
  { emoji: "🌽", name: "corn", keywords: ["vegetable", "yellow", "farm"] },
  { emoji: "🥕", name: "carrot", keywords: ["orange", "vegetable", "healthy"] },
  { emoji: "🍕", name: "pizza", keywords: ["slice", "italy", "cheese"] },
  { emoji: "🍔", name: "burger", keywords: ["hamburger", "fast food", "beef"] },
  { emoji: "🌮", name: "taco", keywords: ["mexican", "shell", "food"] },
  { emoji: "🍣", name: "sushi", keywords: ["japanese", "raw fish", "rice"] },
  { emoji: "🍜", name: "ramen", keywords: ["noodles", "soup", "japanese"] },
  { emoji: "🍩", name: "donut", keywords: ["sweet", "pastry", "ring"] },
  { emoji: "🎂", name: "birthday cake", keywords: ["cake", "celebrate", "candle"] },
  { emoji: "🍪", name: "cookie", keywords: ["sweet", "chocolate", "bake"] },
  { emoji: "🍫", name: "chocolate", keywords: ["sweet", "bar", "candy"] },
  { emoji: "🍭", name: "lollipop", keywords: ["candy", "sweet", "swirl"] },
  { emoji: "🧁", name: "cupcake", keywords: ["sweet", "frosting", "bake"] },
  { emoji: "☕", name: "coffee", keywords: ["hot", "cafe", "morning"] },
  { emoji: "🍵", name: "tea", keywords: ["green", "hot", "calm"] },
  { emoji: "🍺", name: "beer", keywords: ["cheers", "drink", "pub"] },
  { emoji: "🍷", name: "wine", keywords: ["red", "drink", "glass"] },

  // Activities & sports
  { emoji: "⚽", name: "soccer", keywords: ["football", "ball", "sport"] },
  { emoji: "🏀", name: "basketball", keywords: ["ball", "sport", "hoop"] },
  { emoji: "🏈", name: "football", keywords: ["american", "sport", "touchdown"] },
  { emoji: "⚾", name: "baseball", keywords: ["ball", "sport", "pitch"] },
  { emoji: "🎾", name: "tennis", keywords: ["ball", "racket", "sport"] },
  { emoji: "🏊", name: "swimming", keywords: ["swim", "pool", "water"] },
  { emoji: "🚴", name: "cycling", keywords: ["bike", "ride", "sport"] },
  { emoji: "⛷️", name: "skiing", keywords: ["ski", "snow", "winter"] },
  { emoji: "🧘", name: "yoga", keywords: ["meditate", "calm", "stretch"] },
  { emoji: "🎮", name: "video game", keywords: ["gaming", "controller", "play"] },
  { emoji: "🎲", name: "dice", keywords: ["game", "luck", "random"] },
  { emoji: "🎯", name: "bullseye", keywords: ["target", "aim", "direct"] },
  { emoji: "🎨", name: "art", keywords: ["paint", "creative", "palette"] },
  { emoji: "🎸", name: "guitar", keywords: ["music", "rock", "string"] },
  { emoji: "🎹", name: "piano", keywords: ["music", "keyboard", "classical"] },
  { emoji: "🎤", name: "microphone", keywords: ["sing", "karaoke", "perform"] },
  { emoji: "🏆", name: "trophy", keywords: ["winner", "champion", "award"] },
  { emoji: "🥇", name: "gold medal", keywords: ["first", "winner", "best"] },
  { emoji: "🎁", name: "gift", keywords: ["present", "surprise", "wrap"] },
  { emoji: "🎉", name: "party", keywords: ["celebrate", "confetti", "fun"] },

  // Nature & weather
  { emoji: "🌸", name: "blossom", keywords: ["cherry", "spring", "flower", "pink"] },
  { emoji: "🌹", name: "rose", keywords: ["red", "flower", "love", "romance"] },
  { emoji: "🌺", name: "hibiscus", keywords: ["flower", "tropical", "pink"] },
  { emoji: "🌻", name: "sunflower", keywords: ["yellow", "sun", "flower"] },
  { emoji: "🌼", name: "flower", keywords: ["spring", "bloom", "daisy"] },
  { emoji: "🍀", name: "clover", keywords: ["lucky", "green", "four leaf"] },
  { emoji: "🌿", name: "herb", keywords: ["green", "plant", "nature"] },
  { emoji: "🌲", name: "evergreen tree", keywords: ["pine", "forest", "nature"] },
  { emoji: "🌳", name: "tree", keywords: ["nature", "oak", "shade"] },
  { emoji: "🌴", name: "palm", keywords: ["tropical", "beach", "coconut"] },
  { emoji: "🌵", name: "cactus", keywords: ["desert", "prickly", "dry"] },
  { emoji: "🍂", name: "autumn leaves", keywords: ["fall", "orange", "season"] },
  { emoji: "🌱", name: "seedling", keywords: ["grow", "plant", "new"] },
  { emoji: "⭐", name: "star", keywords: ["yellow", "shine", "favorite"] },
  { emoji: "🌙", name: "moon", keywords: ["night", "crescent", "dark"] },
  { emoji: "☀️", name: "sun", keywords: ["bright", "warm", "day"] },
  { emoji: "❄️", name: "snowflake", keywords: ["cold", "winter", "ice"] },
  { emoji: "⚡", name: "lightning", keywords: ["electric", "fast", "storm"] },
  { emoji: "🌈", name: "rainbow", keywords: ["colorful", "hope", "rain"] },
  { emoji: "🌊", name: "wave", keywords: ["ocean", "surf", "water"] },

  // Objects
  { emoji: "💻", name: "laptop", keywords: ["computer", "work", "code"] },
  { emoji: "📱", name: "phone", keywords: ["mobile", "smartphone", "call"] },
  { emoji: "📷", name: "camera", keywords: ["photo", "picture", "shoot"] },
  { emoji: "🔑", name: "key", keywords: ["lock", "access", "open"] },
  { emoji: "💡", name: "lightbulb", keywords: ["idea", "bright", "think"] },
  { emoji: "🔦", name: "flashlight", keywords: ["light", "torch", "dark"] },
  { emoji: "💎", name: "diamond", keywords: ["gem", "precious", "ring"] },
  { emoji: "🔮", name: "crystal ball", keywords: ["magic", "fortune", "predict"] },
  { emoji: "🎩", name: "top hat", keywords: ["magic", "formal", "classy"] },
  { emoji: "🔭", name: "telescope", keywords: ["space", "stars", "observe"] },
  { emoji: "📚", name: "books", keywords: ["study", "library", "read"] },
  { emoji: "🧪", name: "test tube", keywords: ["science", "lab", "experiment"] },
  { emoji: "🧲", name: "magnet", keywords: ["attract", "metal", "pull"] },
  { emoji: "⚙️", name: "gear", keywords: ["settings", "mechanic", "cog"] },
  { emoji: "🛡️", name: "shield", keywords: ["protect", "defense", "armor"] },
  { emoji: "🗺️", name: "map", keywords: ["explore", "travel", "navigate"] },
  { emoji: "🎭", name: "masks", keywords: ["drama", "theater", "art"] },
  { emoji: "🧩", name: "puzzle", keywords: ["piece", "solve", "fit"] },
  { emoji: "🪄", name: "magic wand", keywords: ["magic", "spell", "wizard"] },
  { emoji: "🔐", name: "locked", keywords: ["secure", "private", "key"] },

  // Symbols
  { emoji: "❤️", name: "heart", keywords: ["love", "red", "romance"] },
  { emoji: "🧡", name: "orange heart", keywords: ["love", "warm", "care"] },
  { emoji: "💛", name: "yellow heart", keywords: ["love", "happy", "sunshine"] },
  { emoji: "💚", name: "green heart", keywords: ["love", "nature", "health"] },
  { emoji: "💙", name: "blue heart", keywords: ["love", "calm", "trust"] },
  { emoji: "💜", name: "purple heart", keywords: ["love", "magic", "compassion"] },
  { emoji: "🖤", name: "black heart", keywords: ["dark", "love", "goth"] },
  { emoji: "❤️‍🔥", name: "heart on fire", keywords: ["passion", "burning", "love"] },
  { emoji: "💫", name: "dizzy star", keywords: ["sparkle", "magic", "spin"] },
  { emoji: "✨", name: "sparkles", keywords: ["magic", "glitter", "shine"] },
  { emoji: "🔥", name: "fire", keywords: ["hot", "lit", "flame"] },
  { emoji: "💥", name: "explosion", keywords: ["bang", "boom", "impact"] },
  { emoji: "💯", name: "hundred", keywords: ["perfect", "score", "100"] },
  { emoji: "🎊", name: "confetti ball", keywords: ["celebrate", "party", "fun"] },
  { emoji: "🚩", name: "red flag", keywords: ["warning", "flag", "danger"] },
  { emoji: "♾️", name: "infinity", keywords: ["forever", "endless", "loop"] },
  { emoji: "✅", name: "check", keywords: ["done", "yes", "correct"] },
  { emoji: "❌", name: "cross", keywords: ["no", "wrong", "cancel"] },
  { emoji: "⚠️", name: "warning", keywords: ["caution", "alert", "danger"] },
  { emoji: "🏳️", name: "white flag", keywords: ["surrender", "peace", "blank"] },
];
